project_name: gitprompt
builds:
  - main: ./cmd/gitprompt
    binary: gitprompt
    ldflags: -s -w -X "main.version={{.Version}}" -X "main.commit={{.ShortCommit}}" -X "main.date={{.Date}}" -X "main.goversion={{.Env.GOVERSION}}"
    env:
    - CGO_ENABLED=0
archives:
  - id: tarball
    format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: akupila
      name: homebrew-gitprompt
  name: gitprompt
  homepage: https://github.com/akupila/gitprompt
  description: "git status in the prompt"
